# Generated by Django 6.0 on 2025-12-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='Кабинет №')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='labassistant',
            name='cabinet',
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО Лаборанта'),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Эскертүүлөр'),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон/Моб. номер'),
        ),
        migrations.AddField(
            model_name='labassistant',
            name='cabinets',
            field=models.ManyToManyField(to='accounts.cabinet', verbose_name='Кабинеттер'),
        ),
    ]
