# Generated by Django 6.0 on 2025-12-17 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_issue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='issue',
            name='pc_number',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'Жаңы'), ('seen', 'Көрүлдү'), ('working', 'Иш жүрүп жатат'), ('fixed', 'Жөндөлдү')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='issue',
            name='computer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.computer'),
        ),
        migrations.AddField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
        ),
    ]
