# Generated by Django 6.0 on 2025-12-17 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_computer_room_remove_issue_pc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='issues/'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='computer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.computer'),
            preserve_default=False,
        ),
    ]
