# Generated by Django 6.0 on 2025-12-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_issue_image_alter_issue_computer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labassistant',
            name='cabinets',
        ),
        migrations.DeleteModel(
            name='Cabinet',
        ),
    ]
