# Generated by Django 6.0 on 2025-12-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_labassistant_cabinets_delete_cabinet'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='license',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='office',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='ssd',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('good', 'Жакшы'), ('medium', 'Орто'), ('bad', 'Жаман')], default='good', max_length=10),
        ),
    ]
