# Generated by Django 6.0 on 2025-12-19 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_computer_last_maintenance_computer_license_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='license',
        ),
        migrations.AddField(
            model_name='computer',
            name='license_key',
            field=models.CharField(default='TEMP', max_length=100, verbose_name='Лицензия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='service_date',
            field=models.DateField(default='2025-01-01', verbose_name='Техникалык тейлөө'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='number',
            field=models.IntegerField(verbose_name='ПК №'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='office',
            field=models.CharField(max_length=50, verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.CharField(max_length=100, verbose_name='Операциялык система'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(max_length=50, verbose_name='RAM'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.room', verbose_name='Аудитория'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ssd',
            field=models.CharField(max_length=50, verbose_name='SSD'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('good', 'Жакшы'), ('medium', 'Орто'), ('bad', 'Жаман')], default='good', max_length=10, verbose_name='Статус'),
        ),
    ]
