# Generated by Django 6.0 on 2025-12-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_computer_last_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labassistant',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='accounts.room', verbose_name='Кабинеттер'),
        ),
    ]
