# Generated by Django 6.0 on 2025-12-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_labassistant_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='labassistant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='labassistant_images/'),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='accounts.room', verbose_name='Тиешелүү кабинеттер'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Аудиториянын аты'),
        ),
    ]
