# Generated by Django 6.0 on 2025-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_labassistant_profile_image_alter_labassistant_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Аудиториянын аты'),
        ),
    ]
