# Generated by Django 6.0 on 2025-12-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Эскертүү'),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='labassistants/'),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='accounts.room', verbose_name='Кабинеттер'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
