# Generated by Django 6.0 on 2025-12-25 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_room_description_alter_labassistant_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='license_key',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='room',
        ),
        migrations.AlterField(
            model_name='computer',
            name='number',
            field=models.PositiveIntegerField(verbose_name='ПК №'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='os',
            field=models.CharField(max_length=100, verbose_name='ОС'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='accounts.room'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('good', 'Жакшы'), ('medium', 'Орто'), ('bad', 'Жаман')], default='good', max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='accounts.computer'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(verbose_name='Проблема'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, verbose_name='Сүрөттөмө'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Кабинет'),
        ),
        migrations.CreateModel(
            name='ComputerLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(max_length=150, verbose_name='Лицензия ключу')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='accounts.computer')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Техникалык тейлөө күнү')),
                ('description', models.TextField(verbose_name='Жасалган иш')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='accounts.computer')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('daily', 'Күнүмдүк'), ('weekly', 'Жумалык'), ('monthly', 'Айлык')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('planned', 'Пландалган'), ('done', 'Аткарылды'), ('problem', 'Проблема бар')], default='planned', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyPlan',
        ),
    ]
