# Generated by Django 6.0 on 2025-12-26 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_computer_license_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.computer'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('new', 'Жаңы'), ('seen', 'Көрүлдү'), ('working', 'Иш жүрүп жатат'), ('fixed', 'Жөндөлдү')], default='new', max_length=20),
        ),
    ]
