# Generated by Django 6.0 on 2026-01-15 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_issue_room_alter_issue_computer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='plan',
            name='end_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(help_text='Жума/ай ичинде аткарыла турган иштер'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('weekly', 'Жумалык'), ('monthly', 'Айлык')], max_length=10),
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('arrived_at', models.TimeField(verbose_name='Келген убактысы')),
                ('arrival_photo', models.ImageField(upload_to='daily_reports/arrival/', verbose_name='Келгендеги сүрөт')),
                ('comment', models.TextField(blank=True, verbose_name='Кошумча комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('author', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аткарыла турган иш')),
                ('status', models.CharField(choices=[('done', 'Аткарылды'), ('problem', 'Аткарылган жок')], max_length=10)),
                ('problem_reason', models.TextField(blank=True, verbose_name='Аткарылбаса себеби')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.dailyreport')),
            ],
        ),
    ]
