# Generated by Django 6.0 on 2026-01-15 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_plan_date_remove_plan_is_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='arrival_photo',
            field=models.ImageField(blank=True, null=True, upload_to='daily_reports/'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='arrived_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='problem_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='status',
            field=models.CharField(choices=[('done', 'Аткарылды'), ('problem', 'Проблема')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('daily', 'Күнүмдүк'), ('weekly', 'Жумалык'), ('monthly', 'Айлык')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='created_at',
        ),
    ]
