# Generated by Django 6.0 on 2026-01-17 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_dailyreport_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='problem_reason',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='report',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='status',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Ачык'), ('closed', 'Жабылды')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailytask',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.dailyplan'),
        ),
    ]
