# Generated by Django 6.0 on 2026-01-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_dailytask_problem_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='status',
        ),
        migrations.AddField(
            model_name='plan',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='plan_photos/'),
        ),
    ]
