# Generated by Django 6.0 on 2026-01-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_plan_status_plan_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='plan',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='accounts.dailyplan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.dailyplan'),
            preserve_default=False,
        ),
    ]
