# Generated by Django 6.0 on 2026-01-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_dailyreport_author_remove_dailyreport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('daily', 'Күнүмдүк'), ('weekly', 'Жумалык'), ('monthly', 'Айлык')], default='weekly', max_length=10),
        ),
    ]
