# Generated by Django 6.0 on 2026-01-26 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_longtermplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerservice',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='dailyplan',
            name='author',
        ),
        migrations.RemoveField(
            model_name='dailytask',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='room',
        ),
        migrations.RemoveField(
            model_name='longtermplan',
            name='author',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='author',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='number',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='office',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='os',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ssd',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='status',
        ),
        migrations.AddField(
            model_name='computer',
            name='hdd_capacity',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Объем жест.диска'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor_name',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Монитор аты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor_number',
            field=models.CharField(default='Неизвестно', max_length=50, verbose_name='Монитор №'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Материн.плата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='power_supply',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Блок питания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='processor',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Процессор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='responsible_labassistant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='computer',
            name='system_block_name',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Системный блок аты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='system_block_number',
            field=models.CharField(default='Неизвестно', max_length=50, verbose_name='Системный блок №'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='video_card',
            field=models.CharField(default='Неизвестно', max_length=100, verbose_name='Видеокарта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labassistant',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Өмүр баяны'),
        ),
        migrations.AddField(
            model_name='labassistant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='labassistants/resumes/', verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(max_length=100, verbose_name='Опер.память'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('arrival_time', models.TimeField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('late', models.BooleanField(default=False, verbose_name='Кечикти')),
                ('labassistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Долбоордун аты')),
                ('description', models.TextField(blank=True, verbose_name='Сүрөттөмө')),
                ('start_date', models.DateField(verbose_name='Башталган күнү')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Аяктоо күнү')),
                ('labassistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Иш планы')),
                ('description', models.TextField(blank=True, verbose_name='Сүрөттөмө')),
                ('status', models.CharField(choices=[('planned', 'Пландалган'), ('in_progress', 'Иштелүүдө'), ('done', 'Бүттү')], default='planned', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.project')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/', verbose_name='Файл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.task')),
            ],
        ),
        migrations.DeleteModel(
            name='ComputerLicense',
        ),
        migrations.DeleteModel(
            name='ComputerService',
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
        migrations.DeleteModel(
            name='DailyPlan',
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
        migrations.DeleteModel(
            name='LongTermPlan',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
