# Generated by Django 6.0 on 2026-01-27 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_computerservice_computer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='arrival_time',
            field=models.TimeField(verbose_name='Келген убактысы'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='labassistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.labassistant', verbose_name='Лаборант'),
        ),
    ]
