# Generated by Django 6.0 on 2026-01-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_attendance_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(upload_to='attendance_photos/'),
        ),
    ]
