# Generated by Django 6.0 on 2026-01-27 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_attendance_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labassistant',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='labassistant',
            name='resume',
        ),
        migrations.AddField(
            model_name='labassistant',
            name='role',
            field=models.CharField(choices=[('laborant', 'Лаборант'), ('leader', 'Жетекчи')], default='laborant', max_length=10, verbose_name='Ролу'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labassistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.labassistant', verbose_name='Лаборант'),
        ),
    ]
