# Generated by Django 6.0 on 2026-01-27 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_labassistant_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/', verbose_name='Файл (милдеттүү эмес)'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Активдүү'), ('pausiert', 'Паузада'), ('abgeschlossen', 'Бүткөн')], default='aktiv', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Сүрөттөмө'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labassistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.labassistant'),
        ),
    ]
