# Generated by Django 6.0 on 2026-01-27 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_project_attachment_project_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='task',
        ),
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, verbose_name='Сүрөттөмө'),
        ),
        migrations.AddField(
            model_name='report',
            name='labassistant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.labassistant', verbose_name='Лаборант'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='project',
            field=models.ForeignKey(default=1, limit_choices_to={'status': 'abgeschlossen'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.project', verbose_name='Долбоор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Иштелүүдө'), ('completed', 'Аткарылды'), ('planned', 'Пландалган')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='Старый отчет', max_length=255, verbose_name='Отчеттун аты'),
            preserve_default=False,
        ),
    ]
