# Generated by Django 6.0 on 2026-01-28 09:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_report_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['room__name', 'number'], 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютерлер'},
        ),
        migrations.RemoveField(
            model_name='computer',
            name='hdd_capacity',
        ),
        migrations.AddField(
            model_name='computer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='ip_address',
            field=models.CharField(blank=True, help_text='Компьютердин IP дареги', max_length=15, verbose_name='IP дареги'),
        ),
        migrations.AddField(
            model_name='computer',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Акыркы техникалык тейлөө'),
        ),
        migrations.AddField(
            model_name='computer',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Компьютердин MAC дареги', max_length=17, verbose_name='MAC дареги'),
        ),
        migrations.AddField(
            model_name='computer',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Кийинки техникалык тейлөө'),
        ),
        migrations.AddField(
            model_name='computer',
            name='notes',
            field=models.TextField(blank=True, help_text='Кошумча эскертүүлөр', verbose_name='Эскертүүлөр'),
        ),
        migrations.AddField(
            model_name='computer',
            name='number',
            field=models.CharField(blank=True, help_text='Компьютердин номер', max_length=50, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(choices=[('windows_10', 'Windows 10'), ('windows_11', 'Windows 11'), ('linux', 'Linux'), ('macos', 'macOS'), ('other', 'Башка')], default='windows_10', max_length=50, verbose_name='Операциялык система'),
        ),
        migrations.AddField(
            model_name='computer',
            name='os_version',
            field=models.CharField(blank=True, help_text='ОС версиясы (мисалы: 21H2)', max_length=50, verbose_name='ОС версиясы'),
        ),
        migrations.AddField(
            model_name='computer',
            name='position_x',
            field=models.IntegerField(default=100, help_text='Картадагы X координаты', verbose_name='X позициясы'),
        ),
        migrations.AddField(
            model_name='computer',
            name='position_y',
            field=models.IntegerField(default=100, help_text='Картадагы Y координаты', verbose_name='Y позициясы'),
        ),
        migrations.AddField(
            model_name='computer',
            name='status',
            field=models.CharField(choices=[('gut', '🟢 Жакшы'), ('mittel', '🟡 Орто'), ('schlecht', '🔴 Жаман')], default='gut', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='computer',
            name='storage',
            field=models.CharField(default='512GB SSD', help_text='Жесткий дисктин көлөмү жана түрү', max_length=100, verbose_name='Жест.диск (HDD/SSD)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='monitor_name',
            field=models.CharField(help_text='Монитордун аты/модели', max_length=100, verbose_name='Монитор аты'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='monitor_number',
            field=models.CharField(help_text='Монитордун инвентардык номер', max_length=50, verbose_name='Монитор №'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(help_text='Энелик платанын аты/модели', max_length=100, verbose_name='Энелик плата'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='power_supply',
            field=models.CharField(help_text='Блок питаниенин кубаты', max_length=100, verbose_name='Блок питание'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.CharField(help_text='Процессордун аты/модели', max_length=100, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(help_text='RAM саны жана ылдамдыгы', max_length=100, verbose_name='Оперативдик эс (RAM)'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='responsible_labassistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computers', to='accounts.labassistant', verbose_name='Жооптуу лаборант'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='accounts.room', verbose_name='Бөлмө'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='system_block_name',
            field=models.CharField(help_text='Системный блоктун аты/модели', max_length=100, verbose_name='Блок аты'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='system_block_number',
            field=models.CharField(help_text='Системный блоктун инвентардык номер', max_length=50, verbose_name='Блок/инв. №'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='video_card',
            field=models.CharField(help_text='Видеокартанын аты/модели', max_length=100, verbose_name='Видеокарта'),
        ),
    ]
