# Generated by Django 6.0 on 2026-01-28 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_computer_options_remove_computer_hdd_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='mac_address',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='monitor_name',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='monitor_number',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='next_maintenance',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='position_x',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='position_y',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='responsible_labassistant',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='system_block_name',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='system_block_number',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='computer',
            name='block',
            field=models.CharField(default='Standard PC', help_text='Системный блоктун аты/модели', max_length=100, verbose_name='Блок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='block_inv',
            field=models.CharField(default='BL-001', help_text='Системный блоктун инвентардык номер', max_length=50, verbose_name='Блок/инв.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='hdd',
            field=models.CharField(default='Standard Monitor', help_text='Жесткий дисктин көлөмү жана түрү', max_length=100, verbose_name='Жест.диск'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.CharField(default='MN-001', help_text='Монитордун аты/модели', max_length=100, verbose_name='Монитор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor_inv',
            field=models.CharField(default='Standard Motherboard', help_text='Монитордун инвентардык номер', max_length=50, verbose_name='Монитор/инв.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='number',
            field=models.CharField(help_text='Компьютердин номер', max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(help_text='RAM саны жана ылдамдыгы', max_length=100, verbose_name='Оперативдик эс'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computers', to='accounts.room', verbose_name='Кабинет'),
        ),
    ]
