# Generated by Django 4.2.27 on 2026-02-04 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0030_remove_computer_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=True, verbose_name='Инвентаризация жабык')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Ачык болгонго чейин')),
                ('last_inventory_date', models.DateField(auto_now_add=True, verbose_name='Акыркы инвентаризация күнү')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Жабылган (активацияланган) адам')),
            ],
            options={
                'verbose_name': 'Инвентаризациянын жаздырылышы',
                'verbose_name_plural': 'Инвентаризациянын жаздырылыштары',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
