# Generated by Django 4.2.27 on 2026-02-05 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0031_inventorylock_delete_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylock',
            options={'verbose_name': 'Инвентаризациянын блоктоосу', 'verbose_name_plural': 'Инвентаризациянын блоктоолору'},
        ),
        migrations.RemoveField(
            model_name='inventorylock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorylock',
            name='last_inventory_date',
        ),
        migrations.RemoveField(
            model_name='inventorylock',
            name='locked_until',
        ),
        migrations.AddField(
            model_name='inventorylock',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventorylock',
            name='is_locked',
            field=models.BooleanField(default=True, verbose_name='Доступ жабык'),
        ),
        migrations.AlterField(
            model_name='inventorylock',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Блоктоочу/Ачучу'),
        ),
    ]
