# Generated by Django 4.2.27 on 2026-02-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_alter_inventorylock_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчёт', 'verbose_name_plural': 'Отчёттор'},
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('aktiv', 'Активдүү'), ('pausiert', 'Пландалган'), ('abgeschlossen', 'Бүткөн')], default='aktiv', max_length=20, verbose_name='Статус'),
        ),
    ]
