# Generated by Django 4.2.27 on 2026-04-09 04:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_report_options_remove_report_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date'], 'verbose_name': 'Келүү жазуусу', 'verbose_name_plural': 'Келүү журналы'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='arrival_time',
            field=models.TimeField(verbose_name='Келүү убактысы'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Кечигүүнүн себеби'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_photos/%Y/%m/', verbose_name='Сүрөт'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('labassistant', 'date')},
        ),
    ]
