# Generated by Django 4.2.27 on 2026-04-09 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Иш план', 'verbose_name_plural': 'Ишплан'},
        ),
        migrations.AddField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Башка лаборанттар жана жетекчи көрө алат', verbose_name='Жарыяланган'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_attachments/%Y/%m/', verbose_name='Файл (милдеттүү эмес)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labassistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.labassistant', verbose_name='Лаборант'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активдүү'), ('paused', 'Паузада'), ('completed', 'Бүткөн')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Иш пландын аты'),
        ),
    ]
