# Generated by Django 4.2.27 on 2026-04-10 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_project_options_alter_project_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(limit_choices_to={'status': 'completed'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.project', verbose_name='Долбоор'),
        ),
    ]
