# Generated by Django 4.2.27 on 2026-04-10 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_report_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, verbose_name='Баяндама'),
        ),
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(limit_choices_to={'status': 'completed'}, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.project', verbose_name='Иш план'),
        ),
    ]
