# Generated by Django 4.2.27 on 2026-04-10 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0038_alter_report_description_alter_report_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['room__name', 'block_inv'], 'verbose_name': 'Компьютер', 'verbose_name_plural': 'Компьютерлер'},
        ),
        migrations.RemoveField(
            model_name='computer',
            name='block',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='hdd',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='number',
        ),
        migrations.AddField(
            model_name='computer',
            name='hdd_size',
            field=models.CharField(default=256, help_text='Дисктин өлчөмү (мис.: 500 ГБ)', max_length=50, verbose_name='Катуу дисктин өлчөмү'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='hdd_type',
            field=models.CharField(choices=[('HDD', 'HDD'), ('SSD', 'SSD'), ('HDD+SSD', 'HDD + SSD')], default='HDD', max_length=10, verbose_name='Катуу дисктин түрү'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='block_inv',
            field=models.CharField(help_text='Системалык блоктун инвентардык номери', max_length=50, verbose_name='Системалык блок инв. №'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='monitor',
            field=models.CharField(help_text='Монитордун маркасы же модели (мис.: Acer V206HQL)', max_length=100, verbose_name='Монитор'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='monitor_inv',
            field=models.CharField(help_text='Монитордун инвентардык номери', max_length=50, verbose_name='Монитор инв. №'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='motherboard',
            field=models.CharField(help_text='Эне платанын аты же модели (мис.: ASUS H110M-K)', max_length=100, verbose_name='Эне плата'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='power_supply',
            field=models.CharField(help_text='Системалык блоктун маркасы же кубаты (мис.: 500W)', max_length=100, verbose_name='Системалык блок'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='processor',
            field=models.CharField(help_text='Процессордун аты же модели (мис.: Intel Core i5-9400F)', max_length=100, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ram',
            field=models.CharField(help_text='RAM өлчөмү жана ылдамдыгы (мис.: 8 ГБ DDR4)', max_length=100, verbose_name='Оперативдүү эс (RAM)'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='video_card',
            field=models.CharField(blank=True, help_text='Видеокартанын аты же модели (мис.: NVIDIA GeForce GTX 1050)', max_length=100, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='inventorylock',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Өзгөртүлгөн убакыт'),
        ),
        migrations.AlterField(
            model_name='inventorylock',
            name='is_locked',
            field=models.BooleanField(default=True, verbose_name='Кирүү жабык'),
        ),
        migrations.AlterField(
            model_name='inventorylock',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Аткарган колдонуучу'),
        ),
    ]
