# Generated by Django 4.2.27 on 2026-04-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_computer_options_remove_computer_block_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарийлер'},
        ),
        migrations.AlterModelOptions(
            name='labassistant',
            options={'verbose_name': 'Лаборант', 'verbose_name_plural': 'Лаборанттар'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Иш план', 'verbose_name_plural': 'Иш пландар'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеттор'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеттер'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.labassistant', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Жазылган убакыт'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.project', verbose_name='Иш план'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='Тиркеме'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Сүрөттөмө'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Аяктоо күнү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Жарыяланган'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labassistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.labassistant', verbose_name='Лаборант'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Башталган күнү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активдүү'), ('paused', 'Паузада'), ('completed', 'Бүткөн')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Кошумча маалымат'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Файл'),
        ),
    ]
