# Generated by Django 4.2.27 on 2026-04-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_comment_options_alter_labassistant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labassistant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='Файл'),
        ),
    ]
