# Generated by Django 4.2.28 on 2026-05-26 03:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0042_alter_labassistant_profile_image_alter_report_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарийлер'},
        ),
        migrations.AlterModelOptions(
            name='labassistant',
            options={'verbose_name': 'Лаборант', 'verbose_name_plural': 'Лаборанттар'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-start_date'], 'verbose_name': 'Иш план', 'verbose_name_plural': 'Иш пландар'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отчет', 'verbose_name_plural': 'Отчеттор'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Кабинет', 'verbose_name_plural': 'Кабинеттер'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.labassistant', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Жазылган убакыт'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.project', verbose_name='Иш план'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='video_card',
            field=models.CharField(blank=True, help_text='Видеокартанын аты же модели', max_length=100, verbose_name='Видеокарта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='Тиркеме'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Сүрөттөмө'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Аяктоо күнү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Жарыяланган'),
        ),
        migrations.AlterField(
            model_name='project',
            name='labassistant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.labassistant', verbose_name='Лаборант'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Башталган күнү'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активдүү'), ('paused', 'Паузада'), ('completed', 'Бүткөн')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Аталышы'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Кошумча маалымат'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='practitioners/%Y/', verbose_name='Сүрөт')),
                ('course', models.IntegerField(choices=[(1, '1-курс'), (2, '2-курс'), (3, '3-курс'), (4, '4-курс')], verbose_name='Курс')),
                ('group', models.CharField(help_text='мис.: КИ-21', max_length=50, verbose_name='Топ')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Окуу жайы')),
                ('practice_start', models.DateField(verbose_name='Практика башталышы')),
                ('practice_end', models.DateField(blank=True, help_text='Бош калтырсаңыз автоматтык эсептелет', null=True, verbose_name='Практика аяктоосу')),
                ('duration_days', models.PositiveIntegerField(help_text='1-курс: 12, 2-курс: 36, 3-курс: 48 же 36, 4-курс: 36', verbose_name='Мөөнөт (иш күн)')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practitioners', to='accounts.room', verbose_name='Кабинет')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_practitioners', to='accounts.labassistant', verbose_name='Жооптуу лаборант')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Колдонуучу')),
            ],
            options={
                'verbose_name': 'Практикант',
                'verbose_name_plural': 'Практиканттар',
                'ordering': ['course', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(choices=[(1, '1-курс'), (2, '2-курс'), (3, '3-курс'), (4, '4-курс')], verbose_name='Курс')),
                ('day_number', models.PositiveIntegerField(help_text='Практиканын нечинчи иш күнүнүн планы (1-ден башталат)', verbose_name='Күн номери')),
                ('title', models.CharField(max_length=255, verbose_name='Иш пландын аты')),
                ('description', models.TextField(verbose_name='Мазмуну')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='daily_plans/%Y/%m/', verbose_name='Файл (нускамалар, материалдар)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убакыт')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган убакыт')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to='accounts.labassistant', verbose_name='Түзгөн')),
            ],
            options={
                'verbose_name': 'Күнүмдүк иш план',
                'verbose_name_plural': 'Күнүмдүк иш пландар',
                'ordering': ['course', 'day_number'],
                'unique_together': {('course', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='PractitionerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('arrival_time', models.TimeField(verbose_name='Келүү убактысы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pract_attendance/%Y/%m/', verbose_name='Сүрөт')),
                ('late', models.BooleanField(default=False, verbose_name='Кечикти')),
                ('comment', models.TextField(blank=True, verbose_name='Кечигүүнүн себеби')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.practitioner', verbose_name='Практикант')),
            ],
            options={
                'verbose_name': 'Практиканттын келүүсү',
                'verbose_name_plural': 'Практиканттардын келүүлөрү',
                'ordering': ['-date'],
                'unique_together': {('practitioner', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PlanCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField(help_text='Бүгүн эмне аткарылды?', verbose_name='Отчёт тексти')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='plan_reports/%Y/%m/', verbose_name='Файл (скриншот, документ)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Жиберилген убакыт')),
                ('status', models.CharField(choices=[('submitted', 'Жиберилди'), ('lab_reviewed', 'Лаборант текшерди'), ('approved', 'Бекитилди'), ('rejected', 'Кайтарылды')], default='submitted', max_length=20, verbose_name='Статус')),
                ('lab_feedback', models.TextField(blank=True, verbose_name='Лаборанттын комментарийи')),
                ('lab_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Лаборант текшерген убакыт')),
                ('leader_approved', models.BooleanField(default=False, verbose_name='Жетекчи бекитти')),
                ('leader_feedback', models.TextField(blank=True, verbose_name='Жетекчинин комментарийи')),
                ('leader_approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Жетекчи бекиткен убакыт')),
                ('lab_checked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_completions', to='accounts.labassistant', verbose_name='Текшерген лаборант')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='accounts.dailyplan', verbose_name='Иш план')),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='accounts.practitioner', verbose_name='Практикант')),
            ],
            options={
                'verbose_name': 'Иш план отчёту',
                'verbose_name_plural': 'Иш план отчёттору',
                'ordering': ['-submitted_at'],
                'unique_together': {('practitioner', 'plan')},
            },
        ),
    ]
