# Generated by Django 4.2.28 on 2026-06-29 05:36

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_comment_options_alter_labassistant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='practitioner',
            options={},
        ),
        migrations.AlterField(
            model_name='dailyplan',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=accounts.utils.daily_plan_upload_path, verbose_name='Файл (нускамалар, материалдар)'),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.profile_image_upload_path),
        ),
        migrations.AlterField(
            model_name='labassistant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=accounts.utils.resume_upload_path, verbose_name='Резюме'),
        ),
        migrations.AlterField(
            model_name='plancompletion',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=accounts.utils.plan_completion_upload_path, verbose_name='Файл (скриншот, документ)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=accounts.utils.project_upload_path, verbose_name='Тиркеме'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=accounts.utils.report_upload_path, verbose_name='Файл'),
        ),
    ]
