# Generated by Django 4.2.28 on 2026-06-29 11:09

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_practitioner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practitioner',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.practitioner_photo_upload_path),
        ),
    ]
